plugins {
    id 'com.android.application'
}

android {
    namespace 'com.locatube.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.locatube.app"
        minSdk 21
        targetSdk 34
        versionCode 15
        versionName "1.6.4"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
